### ISSUE TITLE
Extraneous "or" in 4.3.5 (35)

### ISSUE THREAD

**Issue by ronan-d** [Ada-Rapporteur-Group/UCI-Prototype#101]
That word is a leftover from a previous version of the clause, and can potentially confuse readers in my opinion.

**Comment by ARG-Editor** [comment]
Thanks. There's no problem in the (unpublished, unfinished) draft 2 that I am using, so I presume this problem was in draft 1. (Aside, it helps to identify the version of the RM that you are using when you report problems; sometimes even the format matters.)

Since there is no applicable standardization document yet, the wording in the AI (what was approved by the ARG and WG 9) is the "correct" wording. When draft 1 was created, I hadn't yet ported the tool that compares AI wording to the RM wording. So there are many typos (and missing changes) in draft 1. That tool now has been (re)created, so that's probably why the typo you saw was already fixed.

Since the AI is correct, and the RM is currently correct, nothing is needed here. So I'll close this issue.

**Comment by sttaft** [comment]
Good catch, Ronan.  The current online version (Ada 202y Draft 1) does have an extra "or".
