### ISSUE TITLE
Mismatch between definition of subprogram [Wide_]Wide_Hash and position in Annex Q

### ISSUE THREAD

**Issue by reed-hayden** [Ada-Rapporteur-Group/UCI-Prototype#107]
The function Ada.Strings.Hash is defined in A.4.9 (2/5).
Additionally A.4.7 (29/3) and A.4.8 (29/3) note that there are corresponding functions Ada.Strings.Wide_Hash and Ada.Strings.Wide_Wide_Hash.

The function Ada.Strings.Hash is located in Annex Q under Q.3 Language-Defined Subprograms.
However, Ada.Strings.[[Wide_]Wide_]Hash is located in Q.1 Language-Defined Packages.

I believe the functions should be moved to the correct Annex Subclause.

This mismatch also exists for the functions Ada.Strings.[Wide_]Wide_Hash_Case_Insensitive.

**Comment by sttaft** [comment]
Thanks for the bug report!

**Comment by ARG-Editor** [comment]
The same mistake also occurs for functions Ada.Strings.[Wide_]Wide_Equal_Case_Insensitive.

At least I'm consistent. :-)

Indexing is considered non-normative, so it is recorded in AI22-0005-1 and just
fixed in the working draft (which I have already done). No ARG action is required,
so I have closed this issue.
