### ISSUE TITLE
allowing Type_Invariant on non-private types

### ISSUE THREAD

**Issue by evanescente-ondine** [Ada-Rapporteur-Group/UCI-Prototype#115]
Currently Type_Invariant is only allowed on private type or their full view in the private part (RM 2022 7.3.2(2/3):
> Type_Invariant
This aspect shall be specified by an expression, called an invariant expression. Type_Invariant may be specified on a private_type_declaration, on a private_extension_declaration, or on a full_type_declaration that declares the completion of a private type or private extension.

I don't  see why vanilla, fully public type declarations should be denied the benefit of type invariants. I tried to use it to make sure an array was well ordered, and not add tons of preconditions to its operations. Plus static tools can pick it up and see that it stays that way inside operations. It's a very natural construction regardless of the type.

> procedure main is
  type ArrayInput is array (Positive range <>) of Integer
    with Type_Invariant => (for all I in ArrayInput(1..ArrayInput'Last-1) => ArrayInput(I).K < ArrayInput(I+1).K); 
begin
  null;
end main;

**Comment by Richard-Wai** [comment]
I think what you are  looking for here are subtype predicates (3.4.2). In this case a dynamic predicate. Type invariants are specifically for private types, hence their location in subclause 7.3. If you replace Type_Invariant with Dynamic_Predicate in the above example, you will get what you're looking for.

**Comment by evanescente-ondine** [comment]
I see, sorry. I read the ARG issues but can't understand the differences in practical uses. I guess I'll go on a need-to-learn basis :+1:

**Comment by ARG-Editor** [comment]
Richard wrote:
 
>I think what you are looking for here are subtype predicates (3.4.2).
>In this case a dynamic predicate. Type invariants are specifically for
>private types, hence their location in clause 7.3.

To clarify this a bit further, for the benefit of future readers:

* Type_Invariants apply only to private types; the checks only apply to the
client view of a type, not to the implementation view. This (mostly) means
that the checks are only made at the interface of a package (on the
primitive operations). A client cannot alter the value of a private type
other than by using those public interfaces, so it is (mostly) safe to check
only there. For a non-private type, the value can be altered anywhere, and
limiting the checks would not provide any sort of guarantee.

* Dynamic_Predicates apply to any (sub)type, they in theory apply
everywhere but are checked only at specific places (mostly those where the
language includes a subtype conversion). As such, they don't provide a
guarantee (either) but the checks will catch the vast majority of issues.

Note that usually one wants to put a Dynamic_Predicate on a subtype, and
have the first subtype not be encumbered by the predicate. That's because
there always seems to be a case where one needs a value not subject to the
check.

This is similar to the case for constrained arrays, when you declare a
constrained array like:

      type Iarr is array (1..10) of Float;

you actually get declarations like:

         type Anon_Iarr is array (Integer range <>) of Float;
         subtype Iarr is Anon_Iarr (1..10);

This happens because predefined operations like "&" and slicing don't make
much sense for a constrained array. It's likely that you will find a few
such cases for your type with a predicate - there's often short-term values
that need to exist without enforcing the restrictions.

            Randy.

**Comment by sttaft** [comment]
Thanks, Randy.  Nice summary.
